# Generated by Django 5.1.5 on 2025-02-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediarecord',
            name='diagnosis_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mediarecord',
            name='diagnosis_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mediarecord',
            name='prescribed_medication_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mediarecord',
            name='prescribed_medication_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mediarecord',
            name='treatment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mediarecord',
            name='treatment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='specialty_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='specialty_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
