# Generated by Django 5.1.5 on 2025-02-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_mediarecord_diagnosis_en_mediarecord_diagnosis_ru_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaRecord',
            new_name='MedicalRecord',
        ),
    ]
