# Generated by Django 5.1.5 on 2025-02-04 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='hospital.patient'),
        ),
    ]
