# Generated by Django 5.1.5 on 2025-02-04 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_feedback_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_history', to='hospital.doctor'),
        ),
    ]
