# Generated by Django 5.1.5 on 2025-02-04 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_feedback_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to='hospital.patient'),
        ),
    ]
