# Generated by Django 5.1.5 on 2025-02-04 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_remove_feedback_doctor_f_feedback_doctor_fe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='doctor_fe',
        ),
        migrations.AddField(
            model_name='feedback',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
            preserve_default=False,
        ),
    ]
